const VOICE_PRESETS = {
    custom: {
        name: "Custom (Oscillator)",
        description: "Standard analog-style oscillator where you select the shape.",
        type: "synth", // 'synth' or 'sampler'
        waveform: "sawtooth",
        poly: true,
        priority: "last",
        attack: 0.1,
        decay: 0.3,
        sustain: 0.5,
        release: 1.0,
        cutoff: 2000,
        resonance: 1
    }
};

const OSC_PRESETS = {
    laget: {
        name: "Laget",
        settings: {
            "waveform": "sawtooth",
            "priority": "last",
            "attack": 0.05,
            "decay": 0,
            "sustain": 1,
            "release": 0.1,
            "cutoff": 8000,
            "resonance": 4,
            "volume": 0.5,
            "poly": false,
            "eqEnabled": true,
            "delayEnabled": true,
            "reverbEnabled": true,
            "eqLow": 15,
            "eqMid": 20,
            "eqHigh": 8,
            "delayTime": 0.28,
            "delayFeedback": 0.18,
            "delayMix": 0.06,
            "verbTime": 2,
            "verbMix": 0.24,
            "distEnabled": false,
            "distDrive": 0.25,
            "distMix": 1,
            "chorusEnabled": false,
            "chorusRate": 0.6,
            "chorusDepth": 0.53,
            "chorusMix": 1,
            "wahEnabled": false,
            "wahRate": 2,
            "wahDepth": 0.5,
            "wahQ": 5,
            "tremEnabled": true,
            "tremRate": 1.3,
            "tremDepth": 0.33,
            "phaserEnabled": false,
            "phaserRate": 2.2,
            "phaserDepth": 0.25,
            "phaserFeedback": 0,
            "compThreshold": -24,
            "compRatio": 12,
            "compAttack": 0.003,
            "compRelease": 0.25
        },
        scale: {
            "E": -50,
            "F#": -50,
            "G#": -50,
            "B": -50
        }
    },
    shepsy: {
        name: "shepsy",
        settings: {
            "waveform": "square",
            "priority": "last",
            "attack": 0.05,
            "decay": 0,
            "sustain": 1,
            "release": 0.1,
            "cutoff": 8000,
            "resonance": 4,
            "volume": 0.5,
            "poly": false,
            "eqEnabled": true,
            "delayEnabled": true,
            "reverbEnabled": true,
            "eqLow": 15,
            "eqMid": 20,
            "eqHigh": 8,
            "delayTime": 0.28,
            "delayFeedback": 0.18,
            "delayMix": 0.06,
            "verbTime": 1.3,
            "verbMix": 0.1,
            "distEnabled": false,
            "distDrive": 0.25,
            "distMix": 1,
            "chorusEnabled": false,
            "chorusRate": 0.6,
            "chorusDepth": 0.53,
            "chorusMix": 1,
            "wahEnabled": false,
            "wahRate": 2,
            "wahDepth": 0.5,
            "wahQ": 5,
            "tremEnabled": true,
            "tremRate": 1.3,
            "tremDepth": 0.33,
            "phaserEnabled": false,
            "phaserRate": 2.2,
            "phaserDepth": 0.25,
            "phaserFeedback": 0,
            "compThreshold": -24,
            "compRatio": 12,
            "compAttack": 0.003,
            "compRelease": 0.25
        },
        scale: {
            "E": -50,
            "F#": -50,
            "G#": -50,
            "B": -50
        }
    }
};
